"""Operator CLI for the research-only prospective macro recorder.

No autonomous collection. No OANDA. No production trading authority.
observed_at_utc is generated by the recorder clock. The operator cannot backdate it.

Canonical command (CWD should be the repository root, or PYTHONPATH must include it):
    python -m reports.decision_quality.macro_prospective_cli collect-due

Data root: MACRO_PROSPECTIVE_DATA_DIR, else repository-relative
data/research/macro/consensus_pit/prospective. Independent of an arbitrary shell CWD
for the data directory; module import still requires the project on sys.path.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

_RECORDER_PATH = Path(__file__).with_name("_macro_prospective_recorder.py")
_SPEC = importlib.util.spec_from_file_location("macro_prospective_recorder", _RECORDER_PATH)
R = importlib.util.module_from_spec(_SPEC)
assert _SPEC is not None and _SPEC.loader is not None
_SPEC.loader.exec_module(R)

_SCHED_PATH = Path(__file__).with_name("_macro_prospective_scheduler.py")
_SCHED_SPEC = importlib.util.spec_from_file_location("macro_prospective_scheduler", _SCHED_PATH)
S = importlib.util.module_from_spec(_SCHED_SPEC)
assert _SCHED_SPEC is not None and _SCHED_SPEC.loader is not None
_SCHED_SPEC.loader.exec_module(S)


def _recorder(root: str | None):
    path = R.resolve_data_root(root)
    return R.bootstrap_store(path)


def _parse_forecast_value(raw: str | None):
    if raw is None or raw == "":
        return None
    try:
        if "." in raw:
            return float(raw)
        return int(raw)
    except ValueError:
        return raw


def _load_artifact(args) -> tuple[bytes, str]:
    if args.artifact:
        p = Path(args.artifact)
        data = p.read_bytes()
        suffix = p.suffix.lstrip(".") or "bin"
        return data, suffix
    if args.text is not None:
        return args.text.encode("utf-8"), "txt"
    raise SystemExit("artifact path (--artifact) or literal evidence (--text) is required")


def cmd_status(args) -> int:
    rec = _recorder(args.root)
    sys.stdout.write(S.ProspectiveScheduler(rec).format_status())
    return 0


def cmd_due(args) -> int:
    rec = _recorder(args.root)
    sys.stdout.write(rec.format_due())
    return 0


def cmd_ingest(args) -> int:
    if getattr(args, "observed_at_utc", None):
        raise SystemExit("OPERATOR_BACKDATE_FORBIDDEN: observed_at_utc is generated by the recorder")
    rec = _recorder(args.root)
    data, suffix = _load_artifact(args)
    calendar_fields = None
    kind = args.kind
    if kind == "ECONOMIC_CALENDAR":
        calendar_fields = {
            "provider": args.calendar_provider,
            "event_name": args.calendar_event_name,
            "scheduled_time": args.calendar_scheduled_time,
            "importance": args.calendar_importance,
            "forecast": _parse_forecast_value(args.forecast_value),
            "previous": _parse_forecast_value(args.calendar_previous),
            "revised_previous": _parse_forecast_value(args.calendar_revised_previous),
            "reference_period": args.reference_period,
            "unit": args.unit,
        }
    kwargs = {
        "macro_event_id": args.event,
        "source_id": args.source_id,
        "series_name": args.series,
        "expectation_type": args.expectation_type,
        "artifact_bytes": data,
        "artifact_suffix": suffix,
        "forecast_value": _parse_forecast_value(args.forecast_value),
        "unit": args.unit,
        "reference_period": args.reference_period,
        "source_publication_utc": args.source_publication_utc,
        "source_updated_utc": args.source_updated_utc,
        "notes": args.notes,
        "observation_kind": kind,
        "calendar_fields": calendar_fields,
        "retrieval_method": "manual",
    }
    out = rec.operator_ingest(**kwargs)
    sys.stdout.write(json.dumps({"status": out.get("status"), "observation_id": (out.get("observation") or {}).get("observation_id"), "observed_at_utc": (out.get("observation") or {}).get("observed_at_utc"), "raw_artifact_hash": (out.get("observation") or {}).get("raw_artifact_hash"), "pre_release": (out.get("observation") or {}).get("pre_release")}, indent=2) + "\n")
    return 0


def cmd_collect_due(args) -> int:
    rec = _recorder(args.root)
    sched = S.ProspectiveScheduler(rec)
    summary = sched.collect_due(dry_run=bool(args.dry_run))
    sys.stdout.write(S.format_collect_result(summary))
    return int(summary.get("exit_code") or 0)


def cmd_official_first_print_recover(args) -> int:
    if args.event_id != "usd_empsit_2026-10-02":
        raise SystemExit("Stage 12 one-shot recovery is limited to usd_empsit_2026-10-02")
    if args.provider != "bls_official":
        raise SystemExit("canonical first print must be bls_official")
    _FP_PATH = Path(__file__).with_name("_macro_prospective_firstprint_stage12.py")
    _FP_SPEC = importlib.util.spec_from_file_location("macro_stage12_cli", _FP_PATH)
    FP = importlib.util.module_from_spec(_FP_SPEC)
    assert _FP_SPEC is not None and _FP_SPEC.loader is not None
    _FP_SPEC.loader.exec_module(FP)
    rec = _recorder(args.root)
    try:
        out = FP.recover(rec=rec, live=bool(args.live))
    except FP.RecoveryClosed as exc:
        sys.stdout.write(json.dumps({"status": "CLOSED", "reason": str(exc), "first_print_record_created": False}, indent=2) + "\n")
        return 1
    sys.stdout.write(json.dumps({"status": out.get("status"), "first_print_record_created": out.get("first_print_record_created"), "source_url": out.get("source_url"), "raw_sha256": out.get("raw_sha256"), "bls_http_requests": out.get("bls_http_requests"), "identity": out.get("identity")}, indent=2, default=str) + "\n")
    return 0 if out.get("status") in {"RECORDED", "ALREADY_EXISTS", "NOT_PROVEN"} else 1


def _stage13():
    path = Path(__file__).with_name("_macro_prospective_evidence_intake_stage13.py")
    spec = importlib.util.spec_from_file_location("macro_stage13_cli", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec is not None and spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def _load_components_json(raw: str | None) -> dict | None:
    if not raw:
        return None
    path = Path(raw)
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return json.loads(raw)


def cmd_evidence_intake(args) -> int:
    S13 = _stage13()
    rec = _recorder(args.root)
    try:
        out = S13.intake(
            rec=rec,
            event_id=args.event_id,
            checkpoint=args.checkpoint,
            source_file=args.file,
            dry_run=bool(args.dry_run),
            displayed=_load_components_json(getattr(args, "components_json", None)),
            provider_id=getattr(args, "provider_id", None),
        )
    except S13.IntakeClosed as exc:
        sys.stdout.write("EVIDENCE INTAKE FAILED\n%s\n" % exc)
        return 1
    sys.stdout.write(S13.format_receipt(out))
    return 0


def cmd_evidence_ingest_values(args) -> int:
    S13 = _stage13()
    rec = _recorder(args.root)
    displayed = _load_components_json(args.components_json)
    if displayed is None:
        raise SystemExit("--components-json is required for value ingest")
    try:
        out = S13.ingest_values(
            rec=rec,
            event_id=args.event_id,
            checkpoint=args.checkpoint,
            evidence_ref=args.evidence_id,
            displayed=displayed,
            provider_id=args.provider_id,
        )
    except S13.IntakeClosed as exc:
        sys.stdout.write("VALUE INGEST FAILED\n%s\n" % exc)
        return 1
    sys.stdout.write(json.dumps(out, indent=2, default=str) + "\n")
    return 0


def cmd_register_official(args) -> int:
    rec = _recorder(args.root)
    now = rec.now()
    R.persist_official_provenance(rec, now, R.official_schedule_excerpts())
    registered = R.register_official_upcoming(rec, now)
    nxt = rec.next_event(now)
    sys.stdout.write(
        json.dumps(
            {
                "registered": [e["macro_event_id"] for e in registered],
                "next_event": None if nxt is None else nxt["macro_event_id"],
                "current_utc": R.to_utc_iso(now),
            },
            indent=2,
        )
        + "\n"
    )
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="macro_prospective_cli", description="Research-only prospective macro recorder CLI")
    p.add_argument(
        "--root",
        default=None,
        help="Recorder root (default: MACRO_PROSPECTIVE_DATA_DIR or repository-relative data/research/macro/consensus_pit/prospective)",
    )
    sub = p.add_subparsers(dest="command", required=True)

    s = sub.add_parser("status", help="Local operator status. Zero external requests.")
    s.set_defaults(func=cmd_status)

    d = sub.add_parser("due", help="Local due checkpoints. Inspect only. Zero external requests.")
    d.set_defaults(func=cmd_due)

    c = sub.add_parser("collect-due", help="Process due checkpoints. No requests unless a source is fully enabled.")
    c.add_argument("--dry-run", action="store_true", help="Inspect only. Zero requests. Zero state writes.")
    c.set_defaults(func=cmd_collect_due)

    r = sub.add_parser("register-official", help="Register next official CPI/Employment/FOMC events already verified from BLS/Fed.")
    r.set_defaults(func=cmd_register_official)

    fp = sub.add_parser(
        "official-first-print-recover",
        help="One-shot official BLS first-print recovery. Does not enable autonomous collection.",
    )
    fp.add_argument("--event-id", default="usd_empsit_2026-10-02", dest="event_id")
    fp.add_argument("--provider", default="bls_official")
    fp.add_argument("--live", action="store_true", help="Perform the bounded official BLS GET. Default is refuse.")
    fp.set_defaults(func=cmd_official_first_print_recover)

    ev = sub.add_parser("evidence-intake", help="Archive a local screenshot/video. Zero external requests.")
    ev.add_argument("--event-id", required=True, dest="event_id")
    ev.add_argument("--checkpoint", required=True)
    ev.add_argument("--file", required=True, dest="file")
    ev.add_argument("--dry-run", action="store_true")
    ev.add_argument("--components-json", default=None, dest="components_json", help="Optional Phase B values after evidence is secured")
    ev.add_argument("--provider-id", default=None, dest="provider_id", help="Required before value ingest. No TE default.")
    ev.set_defaults(func=cmd_evidence_intake)

    evb = sub.add_parser("evidence-ingest-values", help="Ingest operator-transcribed values against secured evidence.")
    evb.add_argument("--event-id", required=True, dest="event_id")
    evb.add_argument("--checkpoint", required=True)
    evb.add_argument("--evidence-id", required=True, dest="evidence_id")
    evb.add_argument("--components-json", required=True, dest="components_json")
    evb.add_argument("--provider-id", required=True, dest="provider_id", help="Explicit approved consensus provider. No TE default.")
    evb.set_defaults(func=cmd_evidence_ingest_values)

    i = sub.add_parser("ingest", help="Manual ingest. observed_at_utc is generated now; backdating is refused.")
    i.add_argument("--event", required=True, dest="event")
    i.add_argument("--source-id", required=True, dest="source_id")
    i.add_argument("--expectation-type", required=True, dest="expectation_type")
    i.add_argument("--series", required=True)
    i.add_argument("--forecast-value", default=None, dest="forecast_value")
    i.add_argument("--unit", default=None)
    i.add_argument("--reference-period", default=None, dest="reference_period")
    i.add_argument("--source-publication-utc", default=None, dest="source_publication_utc")
    i.add_argument("--source-updated-utc", default=None, dest="source_updated_utc")
    i.add_argument("--artifact", default=None, help="Path to preserved evidence bytes")
    i.add_argument("--text", default=None, help="Literal evidence text (retrieval_method=manual)")
    i.add_argument("--notes", default=None)
    i.add_argument("--kind", default="FORECASTER", choices=("FORECASTER", "ECONOMIC_CALENDAR", "MARKET_IMPLIED"))
    i.add_argument("--calendar-provider", default=None, dest="calendar_provider")
    i.add_argument("--calendar-event-name", default=None, dest="calendar_event_name")
    i.add_argument("--calendar-scheduled-time", default=None, dest="calendar_scheduled_time")
    i.add_argument("--calendar-importance", default=None, dest="calendar_importance")
    i.add_argument("--calendar-previous", default=None, dest="calendar_previous")
    i.add_argument("--calendar-revised-previous", default=None, dest="calendar_revised_previous")
    i.add_argument(
        "--observed-at-utc",
        default=None,
        dest="observed_at_utc",
        help=argparse.SUPPRESS,
    )
    i.set_defaults(func=cmd_ingest)
    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
